# Based on the HPA walkthrough at k8s.io https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

kind: Service
apiVersion: v1
metadata:
  name:  php-apache
spec:
  selector:
    run: php-apache
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  80
---
#apiVersion: apps/v1 #v1.9.x
apiVersion: extensions/v1beta1 #v1.8.x
kind: Deployment
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  replicas: 1
  #if you want this deployment to manage existing replicasets
  #specify a selector to match the labels on the existing replicasets
  #this is now required in later api-versions
  selector:
    matchLabels:
      run: php-apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      #the maximum number of pods that can be created above the total desired number during rollout
      maxSurge: 1
      #the maximum number of pods that is unavailable during the rollout
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - image: gcr.io/google_containers/hpa-example
        imagePullPolicy: Always
        name: php-apache
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort:  80
