apiVersion: v1
kind: Pod
metadata:
  name: cm-envfrom
spec:
  containers:
  - name: nginx
    image: nginx
    #here we are saying create a set of environment variables
    #from the content of the app-properties ConfigMap
    envFrom:
    - configMapRef:
        name: app-properties