# 1) Deploy the configmap and this manifest
#
# kubectl create -f app-properties.yml
# kubectl create -f configmap-from-volume.yml
#
# 2) Exec into the pod
#
# kubectl exec -ti cm-volume -- sh
#
# 3) In the shell:
#
# cat /mnt/config/LOG_LEVEL
#
apiVersion: v1
kind: Pod
metadata:
  name: cm-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: config
      mountPath: /mnt/config

  #here we define a volume named config whose source is a configMap
  volumes:
  - name: config
    configMap:
      name: app-properties