apiVersion: v1
kind: Pod
metadata:
  name: cm-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: config
      mountPath: /mnt/config

  #here we define a volume named config whose source is a configMap
  volumes:
  - name: config
    configMap:
      name: app-properties