kind: Pod
apiVersion: v1
metadata:
  name: pod-root
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim
  initContainers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: "/usr/share/simple-http"
      name: pv-storage
    command:
    - echo
    - "Kubernetes is awesome!"
    - >
    - index.html
  containers:
  - name: simple-http
    image: architechbootcamp/simple-http-server:1.0.0
    ports:
    - containerPort: 8080
      name: "http-server"
    env:
    - name: "HTML_DIR"
      value: "/usr/share/simple-http"
    volumeMounts:
    - mountPath: "/usr/share/simple-http"
      #here we mount the volume defined
      #above in volumes
      name: pv-storage