kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheusstorage
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: grafanastorage
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared
