# When enabling RBAC on minikube v0.25.0 the kube-dns and the dashboard will fail to start due to permission issues
# with the default serviceaccount.
#
# Create these ClusterRole/ClusterRoleBindings to add the necessary permissions.
# See https://github.com/kubernetes/minikube/issues/1734

# Wide open access for testing
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-writer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "update", "delete", "patch"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---
# Full read access to the api and resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---
# Give default serviceaccount full write access
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-systemaccount-cluster-write
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-writer
  apiGroup: rbac.authorization.k8s.io

---
  # Give default serviceaccount full write access
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-systemaccount-cluster-read
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io