# RoleBindings grant the privileges defined in a given role
# to a subject (e.g. user) in a given namespace.  RoleBindings
# grant privileges at the namespace level.  To grant privileges at
# the cluster level, use ClusterRoleBindings

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 #for v1.8.0++
#apiVersion: rbac.authorization.k8s.io/v1beta1 #for v1.7.x
metadata:
  name: qa-deployer
  namespace: qa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: qa-role
subjects:
- kind: User
  name: jenkins
  namespace: qa
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: qa
  namespace: qa
  apiGroup: rbac.authorization.k8s.io