version: "3.1"
services:
    mongodb:
        image: mongo 
        ports:
            - "27017:27017"

    todo-api:
        build: ./todo-api     
        image: todo-api
        ports:
            - "80:8080"
        depends_on:
            - mongo-seed
