server:
    port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_URL}
      database: todo-app
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

AzureAD:
  appId: ${AZURE_APP_ID}
  identityMetaData: ${AD_IDENTITY_META_DATA_URL}
logging:
  level:
    root: WARN
    org.springframework.web: ${SPRING_LOG_LEVEL}
    ca.architech: ${APP_LOG_LEVEL}
