# This is the docker-compose settings file leveraged when developing the application outside of it's container.
# It is automatically picked up on `docker-compose up`.
version: '3'
services:
  nginx:
    image: 'nginx:1.13.7'
    command: /bin/bash -c "envsubst '$$AZURE_APP_ID $$IS_TEST_MODE $$AZURE_AD_TENANT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf.template'
    depends_on:
      - todo-api
      - user-api
  mongodb:
    ports:
      - '27017:27017'
    volumes:
      - 'todo-app-data:/data/db'
      - 'todo-app-config-data:/data/config'
  todo-api:
    ports:
      - '8080:8080'
    environment:
      MONGODB_URL: 'mongodb:27017'
      SPRING_LOG_LEVEL: INFO
      APP_LOG_LEVEL: DEBUG
      AZURE_APP_ID: '${AZURE_APP_ID}'
      AD_IDENTITY_META_DATA_URL: '${AZURE_IDENTITY_META_DATA:-https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration}'
      AZURE_CLIENT_SECRET: '${AZURE_CLIENT_SECRET}'
      IS_TEST_MODE: '${IS_TEST_MODE:-false}'
      USER_API_BASE_URL: http://user-api:8082
  user-api-mongodb:
    ports:
      - '27018:27017'
    volumes:
      - 'user-api-data:/data/db'
      - 'user-api-config-data:/data/config'
  user-api:
    ports:
      - '8082:8082'
    environment:
      IS_TEST_MODE: '${IS_TEST_MODE:-false}'
      MONGODB_URL: 'mongodb://user-api-mongodb:27017/user-api'
      LOG_LEVEL: info
      AZURE_IDENTITY_META_DATA: '${AZURE_IDENTITY_META_DATA:-https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration}'
      AZURE_APP_ID: '${AZURE_APP_ID}'
volumes:
  todo-app-data:
    external: false
  todo-app-config-data:
    external: false
  user-api-data:
    external: false
  user-api-config-data:
    external: false
