# 1. Deploy the service and deployment.  Note this also deploys a busybox pod.
# 
# kubectl create -f headless-service.yaml
#
# 2. Get shell acces to the busybox pod
#
# kubectl exec -ti busybox --sh 
#
# 3. In the shell execute the following command.  What do you see?
#
# nslookup headless-service 

kind: Service
apiVersion: v1
metadata:
  name: headless-service
spec:
  #This is what makes it a headless service
  clusterIP: None
  ports:
    - name: nginx 
      port: 80
  selector:
    app: headless-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  headless-nginx
  labels:
    app: headless-nginx
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: headless-nginx 
    spec:
      containers:
      - image:  nginx
        name:  headless-nginx
        imagePullPolicy: Always
        ports:
        - name: nginx
          containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - 'sleep'
      - '100000'
