const actionTypes = {
  REQUEST_TODOS: 'REQUEST_TODOS',
  RECEIVE_TODOS: 'RECEIVE_TODOS',

  ADD_TODO: 'ADD_TODO',
  ADDED_TODO: 'ADDED_TODO',

  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLED_TODO: 'TOGGLED_TODO',

  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};

export default actionTypes;