# Instead, it defines paths that direct the request to specific service.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-app-ingress
annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 192.168.99.100.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: todo-app-ui
          servicePort: 80
      - path: /api/todos
        backend:
          serviceName: todo-api
          servicePort: 80
      - path: /api/user
        backend:
          serviceName: user-api
          servicePort: 80
  #The service that will handle all other
  #paths. e.g. return a 404 not found page.
  backend:
    serviceName: default-http-backend
    servicePort: 80
