apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: todo-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: architechbootcamp/todo-api:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: todo-api-config
              key: db_url
        - name: IS_TEST_MODE
          valueFrom:
            configMapKeyRef:
              name: todo-api-config
              key: is_test_mode
        - name: SPRING_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: todo-api-config
              key: spring_log_level
        - name: APP_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: todo-api-config
              key: app_log_level
        - name: USER_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: todo-api-config
              key: user_api_url
        - name: AZURE_APP_ID
          valueFrom:
            secretKeyRef:
              name: todoapp-secrets
              key: azure_app_id
        - name: AD_IDENTITY_META_DATA_URL
          valueFrom:
            secretKeyRef:
              name: todoapp-secrets
              key: ad_identity_meta_data
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: todoapp-secrets
              key: azure_client_secret
      #imagePullSecrets:
      #  - name: registry_credentials
