version: "3"
services:
    mongodb:
        image: mongo 
        ports:
            - "27017:27017"
        volumes:
            - "todo-app-data:/data/db"
            - "todo-app-config-data:/data/config"

    todo-api:
        build:
            context: ./todo-api-java    
        image: todo-api
        ports:
            - "8080:8080"
        environment:
            MONGODB_URL: mongodb:27017
            SPRING_LOG_LEVEL: INFO
            APP_LOG_LEVEL: DEBUG
            ALLOWED_ORIGINS: '*'
            AZURE_APP_ID: 'ADD APP ID HERE'
            AD_IDENTITY_META_DATA_URL: https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration=
        depends_on:
            - mongodb

    nginx:
        image: nginx:1.13.7
        ports:
            - "80:80"
        volumes:
            - ./todo-ui/nginx.conf:/etc/nginx/conf.d/default.conf
#        networks:
#            hostnet: {}
volumes:
    todo-app-data:
        external: true
    todo-app-config-data:
        external: true

#networks:
#    hostnet:
#        external:
#            name: host
