#This pod runs as NON-root. It will attempt to write to the /mnt/data directory.
#It will FAIL.  Why?  Because to mount the volume, the container must run as root.
#This is a problem!  See non-root-correct-pod.yml
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod-01
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim-01
  initContainers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: "/mnt/data"
      name: pv-storage
      command:
      - sh
      - "-c"
      - |
          #create non-root user and change ownership/permissions to mountpath
          #note the initContainer will run as root
          adduser -DH non-root
          chown -R non-root /mnt/data
          chmod 700 /mnt/data
  containers:
  - name: busybox-root
    image: busybox
    ports:
    - containerPort: 80
      name: "http-server"
    command:
    - sh
    - "-c"
    - |
        if echo "writing to /mnt/data" > /mnt/data/message; then
          echo "successfully wrote to /mnt/data"
        else
          echo "FAILED TO WRITE TO /mnt/data"
        fi
        sleep 1000
    volumeMounts:
    - mountPath: "/mnt/data"
      #here we mount the volume defined
      #above in volumes
      name: pv-storage
  securityContext:
    #Run as user with UID 1000 e.g. non-root
    runAsNonRoot: true
