kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  #when the PVC is released, retain the data.
  #valid values are Retain (default), Recycle and Delete.
  #Not all volume plugins support Recycle. See the volume plugin for details.
  persistentVolumeReclaimPolicy: Retain
  #to deploy to minikube ssh into minikube then create the directory
  #
  # minikube ssh
  # su
  # mkdir /mnt/data
  hostPath:
    path: /mnt/data
  #required on minikube
  storageClassName: standard

    
