
# Note how the 'volumes' attribute has a 'persistentVolumeClaim' attribute.
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod-01
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim-01
  containers:
  - name: pv-container
    image: nginx
    ports:
    - containerPort: 80
      name: "http-server"
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      #here we mount the volume defined
      #above in volumes
      name: pv-storage
