kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-02
spec:
  volumeName: pv-volume
  selector: 
    matchLabels:
       type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi