#An example of a PVC that claims a specific PV using volumeName and labels
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-01
spec:
  #volumeName: pv-volume
  storageClassName: architech-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi