kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qa-role
  namespace: qa
rules:
- verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
  apiGroups: ["*"]
  resources: ["*"]