kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qa-deployer
  namespace: qa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: qa-role
subjects:
- kind: User
  name: jenkins
  namespace: qa
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: qa
  namespace: qa
  apiGroup: rbac.authorization.k8s.io