# Role and ClusterRole objects defines privileges - actions you can perform
# on a given resource within a given apiGroup.
# They are defined locally at the namespace level (Role)
# or globally at the cluster level (ClusterRole)
kind: Role
apiVersion: rbac.authorization.k8s.io/v1 #for v1.8.0++
#apiVersion: rbac.authorization.k8s.io/v1beta1 #for v1.7.x
metadata:
  name: qa-role
  namespace: qa
rules:
- verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
  apiGroups: ["*"]
  resources: ["*"]