server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_URL}
      database: todo-app
AzureAD:
  appId: ${AZURE_APP_ID}
  identityMetaData: https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration
logging:
  level:
    root: WARN
    org.springframework.web: ${SPRING_LOG_LEVEL}
    ca.architech: ${APP_LOG_LEVEL}
