server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_URL}
      database: todo-app
AzureAD:
  appId: "add application id from azure ad here"
  identityMetaData: https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    ca.architech: INFO
