# Note this example does not even specify a host. 
# Instead, it defines paths that direct the request to specific service.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pod-details-ingress-single
spec:
  rules:
  - http:
      paths:
      - path: /pod-details/v1
        backend:
          serviceName: pod-details-v1
          servicePort: 8000
      - path: /pod-details/v2
        backend:
          serviceName: pod-details-v2
          servicePort: 8000
  #The service that will handle all other
  #paths. e.g. return a 404 not found page.
  backend:
    serviceName: default-http-backend
    servicePort: 80
