---
- name: Setup Jenkins build server
  hosts: all
  vars:
    nginx_port: 80
  vars_prompt:
    - name: "admin_username"
      prompt: "Enter admin username:"
    - name: "admin_password"
      prompt: "Enter admin password:"
      private: yes
  pre_tasks:
  # These two pre_tasks are required to be able to install newer version on MySQL on CentOS 7
  # since SonarQube requires MySQL 5.6+ and CentOS 7 comes with MySQL 5.5
    - name: Install the MySQL repo.
      become: yes
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      become: yes
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"

  roles:
    - { role: common, become: yes }
    - { role: nginx, become: yes }
    - { role: geerlingguy.java, java_packages: "java-1.8.0-openjdk", become: yes }
    - { role: geerlingguy.mysql, become: yes }
    - { role: sonar }
    - { role: geerlingguy.jenkins, jenkins_version: "2.93", jenkins_admin_username: "{{ admin_username }}", jenkins_admin_password: "{{ admin_username }}", jenkins_plugins: ["git", "build-pipeline-plugin", "blueocean", "kubernetes", "kubernetes-cd", "azure-acs", "sonar", "pipeline-stage-view"], jenkins_plugins_state: present, become: yes }
    - { role: configure-jenkins, jenkins_admin_username: "{{ admin_username }}", jenkins_admin_password: "{{ admin_username }}", become: yes }
    - { role: kubectl, become: yes }
    - { role: docker, become: yes }
