apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
           - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: architechbootcamp/todo-api:v0.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: db_url
            - name: SPRING_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: spring_log_level
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: app_log_level
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: azure_app_id
            - name: AD_IDENTITY_META_DATA_URL
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: ad_identity
      imagePullSecrets:
        - name: techdemosecret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  # type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: todo-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: web
          image: architechbootcamp/todo-ui:v0.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-web-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-ui
