apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: todo-app
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: todo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
           - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo-app
spec:
  ports:
  - port: 8080
  selector:
    app: todo-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: architechbootcamp/todo-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: db_url
            - name: SPRING_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: spring_log_level
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: app_log_level
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: azure_app_id
            - name: AD_IDENTITY_META_DATA_URL
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: ad_identity
      imagePullSecrets:
        - name: techdemosecret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-web-ui
  namespace:
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-ui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-ui
  namespace: todo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: web
          image: architechbootcamp/todo-ui:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-mongo
  namespace: todo-app
spec:
  replicas: 1
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app:  user-mongo
        tier: data-tier
    spec:
      containers:
        - name:  user-mongo
          image: mongo
          ports:
           - containerPort: 27017
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-api
  namespace: todo-app
spec:
  replicas:  2
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: user-api
        tier: backend
    spec:
      containers:
        - name: user-api
          image: architechbootcamp/user-api:latest
          ports:
            - containerPort: 8082
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: userapi-config
                  key: db_url
            - name: IS_TEST_MODE
              valueFrom:
                configMapKeyRef:
                  name: userapi-config
                  key: is_test_mode
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: userapi-config
                  key: app_log_level
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: azure_app_id
            - name: AZURE_IDENTITY_META_DATA
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: ad_identity
      imagePullSecrets:
        - name: techdemosecret

