apiVersion: v1
kind: Pod
metadata:
  name: busybox-1000
spec:
  containers:
  - name: busybox-1000
    image: busybox
    command:
    - 'sleep'
    - '1000'
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true

      