apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.MongoDb.ServiceName }}
spec:
  ports:
  - port: {{ .Values.MongoDb.ServicePort }}
  selector:
    app: {{ .Values.MongoDb.Name }}
    tier: data-tier
    environment: {{.Values.Global.Environment}}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.MongoDb.Name}}
spec:
  replicas: {{.Values.MongoDb.Replicas}}
  minReadySeconds: 2
  template:
    metadata:
      labels:
        app:  {{ .Values.MongoDb.Name }}
        tier: data-tier
        environment: {{.Values.Global.Environment}}
    spec:
      containers:
      - name:  {{ .Values.MongoDb.Name }}
        image: {{ .Values.MongoDb.Image }}
        ports:
        - containerPort: {{ .Values.MongoDb.ContainerPort }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.MongoDb.PVC }}
---
#Note a default StorageClass needs to be available
#On the cluster
apiVersion:
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.MongoDb.PVC }}
  labels:
    environment: {{ .Values.Global.Environment }}
spec:
  volumeName: {{ .Values.MongoDb.PV }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.MongoDb.PV }}
spec:
  capacity:
    storage: 10Gi
  #only once process can read/write
  accessModes:
    - ReadWriteOnce
  #when the PVC is released, retain the data.
  #valid values are Retain (default), Recycle and Delete.
  #Not all volume plugins support Recycle. See the volume plugin for details.
  persistentVolumeReclaimPolicy: Retain
  # hostPath volume type so the volume is mapped to a path on the node
  hostPath:
    path: {{ .Values.MongoDb.HostPath }}