apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.TodoMongo.ServiceName }}
  namespace: {{.Values.General.NameSpace}}
spec:
  ports:
  - port: {{ .Values.TodoMongo.ServicePort }}
  selector:
    app: {{ .Values.TodoMongo.Name }}
    tier: data-tier
    environment: {{.Values.General.Environment}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TodoAPI.ServiceName }}
  namespace: {{.Values.General.NameSpace}}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.TodoAPI.ServicePort }}
  selector:
    app: {{ .Values.TodoAPI.Name }}
    tier: backend
    environment: {{.Values.General.Environment}}
