apiVersion: v1
kind: Service
metadata:
  name: {{.Values.WebUI.ServiceName}}
  namespace: {{.Values.General.NameSpace}}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.WebUI.ServicePort }}
  selector:
    tier: frontend
    app: {{.Values.WebUI.Name}}
    environment: {{.Values.General.Environment}}
