# Development configuration. Automatically picked up on `docker-compose up`
version: '3'
services:
  mongodb:
    ports:
      - '27017:27017'
    volumes:
      - 'todo-app-data:/data/db'
      - 'todo-app-config-data:/data/config'
  user-api-mongodb:
    ports:
      - '27018:27017'
    volumes:
      - 'user-api-data:/data/db'
      - 'user-api-config-data:/data/config'
  user-api:
    ports:
      - '8082:8082'
    environment:
      IS_TEST_MODE: '${IS_TEST_MODE:-false}'
      MONGODB_URL: 'mongodb://user-api-mongodb:27017/user-api'
      LOG_LEVEL: info
      AZURE_IDENTITY_META_DATA: '${AZURE_IDENTITY_META_DATA:-https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration}'
      AZURE_APP_ID: '${AZURE_APP_ID}'
volumes:
  todo-app-data:
    external: false
  todo-app-config-data:
    external: false
  user-api-data:
    external: false
  user-api-config-data:
    external: false
