version: '3'
services:
  mongodb:
    image: mongo
  user-api-mongodb:
    image: mongo
    ports:
      - '27018:27017'
  user-api:
    build:
      context: ../user-api
    image: user-api
    ports:
      - '8082:8082'
    environment:
      IS_TEST_MODE: '${IS_TEST_MODE:-false}'
      MONGODB_URL: 'mongodb://user-api-mongodb:27017/user-api'
      APP_LOG_LEVEL: info
      AZURE_IDENTITY_META_DATA: 'https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration'
      AZURE_APP_ID: '${AZURE_APP_ID}'
    depends_on:
      - user-api-mongodb
