# Merge this file with docker-compose to be build and run the todo-api container
# `docker-compose -f docker-compose.yml -f docker-compose.build.yml build --no-cache`
# `docker-compose -f docker-compose.yml -f docker-compose.build.yml up`
version: "3"
services:
    todo-api:
        build:
            context: .
        image: todo-api
        ports:
            - "8080:8080"
        environment:
            MONGODB_URL: mongodb:27017
            SPRING_LOG_LEVEL: INFO
            APP_LOG_LEVEL: DEBUG
            ALLOWED_ORIGINS: '*'
            AZURE_APP_ID: 'ADD APP ID HERE'
            AD_IDENTITY_META_DATA_URL: https://login.microsoftonline.com/architech.onmicrosoft.com/v2.0/.well-known/openid-configuration=
        depends_on:
            - mongodb