/*
 Required Plugins:
  - Environment Injector Plugin
   -- Add `GIT_BRANCH=some/branch` when testing pipeline script directly in Jenkins
 Required Credentials:
  - `docker-hub-credentials` : Username and password for docker hub
  - `scm-credentials` : SSH username (git) and private key to access git. Used when testing pipeline script directly in Jenkins
 Required Jobs:
  - `QA-Tests` : Job to execute tests on all components in a QA environment.
 Required Parameters (under "This job is parameterized"):
  - `CleanWorkspace` : Boolean. Default to unchecked.
*/

node {
    final PROJECT_VERSION = '1.0.0'
    final PROJECT_IMAGE_NAME = 'architechbootcamp/todo-api'
    final PROJECT_PATH = 'todo-app/todo-api-java'

    def buildEnv;

    stage('Checkout') {

        if (params.CleanWorkspace) {
            echo "Cleaning Workspace"
            deleteDir()
        }

        echo "Checkout project"
        // Checkout source from the same Git repo/branch this Jenkinsfile resides in.
        checkout scm

        // Checkout source from a specific Git repository
//        git branch: "$GIT_BRANCH", credentialsId: 'scm-credentials', url: 'git@bitbucket.org:architech/k8s-fundamentals.git'
        GIT_REVISION = sh (
                script: 'git rev-parse --short HEAD',
                returnStdout: true
        ).trim()

        echo "Checked out git commit ${GIT_REVISION}"

        // Desclare versions to use in tags later on.
        IMAGE_FULL_VERSION = "${PROJECT_VERSION}_${GIT_REVISION}"
        IMAGE_SEMVER = "${PROJECT_VERSION}"
    }
    stage('Test') {
        def projectName = "todoapi${env.BUILD_NUMBER}";

        try {
            echo "Starting integration tests"
            sh "docker-compose -f $PROJECT_PATH/docker-compose.test.yml -p $projectName run -e FAIL_TESTS=false todo-api-test"
        } finally {
            echo "Shutting down docker-compose environment"
            sh "docker-compose -f $PROJECT_PATH/docker-compose.test.yml -p $projectName down"
        }
    }

    stage('Build') {
        echo "Building image ${PROJECT_IMAGE_NAME}"
        buildEnv = docker.build(PROJECT_IMAGE_NAME,PROJECT_PATH)
    }

    stage('QA Image Push') {
        echo "Pushing QA tags of image to docker registry"
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            QA_IMAGE_FULL_VERSION = "qa_${IMAGE_FULL_VERSION}"
            buildEnv.push(QA_IMAGE_FULL_VERSION)
            buildEnv.push("qa_${IMAGE_SEMVER}")
            buildEnv.push("qa_latest")
        }
    }

    stage('Deploy to QA') {
        //TODO: implement deploy to QA step
    }

    stage('QA Test') {
        echo "Spawning Job to run functional testing on all components in QA environment"
        try {
            build job: 'QA-Tests',
                    parameters:
                            [
                                    string(name: 'imageName', value: PROJECT_IMAGE_NAME),
                                    string(name: 'imageVersion', value: QA_IMAGE_FULL_VERSION)
                            ]
        } catch (error) {
            //TODO: Rollback QA deployment here ?
        }
    }

    stage('Prod Image Push') {
        echo "Pushing Production-ready tags to docker registry"
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            PROD_IMAGE_FULL_VERSION = "${IMAGE_FULL_VERSION}"
            buildEnv.push(PROD_IMAGE_FULL_VERSION)
            buildEnv.push(IMAGE_SEMVER)
            buildEnv.push("latest")
            buildEnv.push("stable")
        }
    }

    stage('Deploy to Prod') {
        input 'Push to Production?'
        //TODO: Push to production
    }

}